"""Snapshots & Change Events domain — SQLAlchemy 2.0 declarative models.

Stores website content snapshots and categorized change events for continuous
competitor monitoring.
"""

from __future__ import annotations

from datetime import datetime
import uuid

from sqlalchemy import DateTime, ForeignKey, Index, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.database import Base


class CompetitorSnapshot(Base):
    """ORM model representing the `competitor_snapshots` table in PostgreSQL.

    Stores crawled homepage and pricing markdown content alongside a SHA256
    content hash to prevent duplicate snapshot creation.
    """

    __tablename__ = "competitor_snapshots"

    __table_args__ = (
        Index("ix_snapshots_competitor_created", "competitor_id", "created_at"),
    )

    # Primary Key
    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        comment="UUID primary key, generated by application layer",
    )

    # Foreign Key
    competitor_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("competitors.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Foreign key referencing competitors.id",
    )

    # SHA256 content hash of combined homepage + pricing markdown
    content_hash: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        index=True,
        comment="SHA256 hex digest of combined crawled content for duplicate detection",
    )

    # Crawled Markdown Contents
    homepage_content: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Raw markdown content scraped from competitor homepage",
    )

    pricing_content: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Raw markdown content scraped from competitor pricing page",
    )

    # Audit Timestamp
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Timestamp when snapshot was taken",
    )

    # Relationships
    competitor: Mapped["Competitor"] = relationship("Competitor", lazy="selectin")

    change_events: Mapped[list["ChangeEvent"]] = relationship(
        "ChangeEvent",
        back_populates="snapshot",
        lazy="select",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return (
            f"<CompetitorSnapshot id={self.id!r} competitor_id={self.competitor_id!r} "
            f"hash={self.content_hash[:10]!r}>"
        )


class ChangeEvent(Base):
    """ORM model representing the `change_events` table in PostgreSQL.

    Stores categorized change events detected between consecutive competitor snapshots.
    Categories: Pricing | Features | Homepage | Hiring | Marketing | Product | Documentation
    """

    __tablename__ = "change_events"

    __table_args__ = (
        Index("ix_change_events_competitor_created", "competitor_id", "created_at"),
    )

    # Primary Key
    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        comment="UUID primary key, generated by application layer",
    )

    # Foreign Keys
    competitor_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("competitors.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Foreign key referencing competitors.id",
    )

    snapshot_id: Mapped[str | None] = mapped_column(
        String(36),
        ForeignKey("competitor_snapshots.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
        comment="Foreign key referencing competitor_snapshots.id",
    )

    # Change Details
    category: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
        comment="Category of change: Pricing | Features | Homepage | Hiring | Marketing | Product | Documentation",
    )

    summary: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="AI-generated summary and business impact assessment of the change",
    )

    added_content: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Highlights of added text/features",
    )

    removed_content: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Highlights of removed text/features",
    )

    impact_score: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
        default="Medium",
        comment="Estimated business impact: High | Medium | Low",
    )

    # Audit Timestamp
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        index=True,
        comment="Timestamp when change event was created",
    )

    # Relationships
    competitor: Mapped["Competitor"] = relationship("Competitor", lazy="selectin")

    snapshot: Mapped["CompetitorSnapshot | None"] = relationship(
        "CompetitorSnapshot",
        back_populates="change_events",
        lazy="selectin",
    )

    def __repr__(self) -> str:
        return (
            f"<ChangeEvent id={self.id!r} competitor_id={self.competitor_id!r} "
            f"category={self.category!r} impact={self.impact_score!r}>"
        )
