"""Reports domain — SQLAlchemy 2.0 declarative model.

Each Report is an AI-generated competitive intelligence analysis
for a single tracked Competitor. Reports are created asynchronously
via background jobs and consumed by PDF generation and email modules.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Index, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.database import Base

# Valid lifecycle states for a report
REPORT_STATUS_PENDING = "pending"
REPORT_STATUS_PROCESSING = "processing"
REPORT_STATUS_COMPLETED = "completed"
REPORT_STATUS_FAILED = "failed"


class Report(Base):
    """ORM model representing the `reports` table in PostgreSQL.

    Stores AI-generated competitive intelligence analysis tied to
    a specific Competitor. The AI pipeline writes each section field
    individually as the analysis progresses.
    """

    __tablename__ = "reports"

    # Composite index: fetch all reports for a competitor ordered by date
    __table_args__ = (
        Index("ix_reports_competitor_created", "competitor_id", "created_at"),
    )

    # ------------------------------------------------------------------
    # Primary Key — UUID generated in Python before INSERT
    # ------------------------------------------------------------------
    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        comment="UUID primary key, generated by application layer",
    )

    # ------------------------------------------------------------------
    # Foreign Key — CASCADE DELETE when competitor is removed
    # ------------------------------------------------------------------
    competitor_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("competitors.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Foreign key to competitors.id — cascades on delete",
    )

    # ------------------------------------------------------------------
    # Report Lifecycle Status
    # Tracks where the report is in the AI processing pipeline.
    # Values: pending | processing | completed | failed
    # ------------------------------------------------------------------
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default=REPORT_STATUS_PENDING,
        server_default=REPORT_STATUS_PENDING,
        index=True,
        comment="AI pipeline status: pending | processing | completed | failed",
    )

    # ------------------------------------------------------------------
    # Core AI Analysis Sections (nullable until AI writes them)
    # ------------------------------------------------------------------
    summary: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Executive summary of the competitive analysis",
    )

    strengths: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="SWOT — competitor strengths identified by the AI agent",
    )

    weaknesses: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="SWOT — competitor weaknesses identified by the AI agent",
    )

    opportunities: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="SWOT — market opportunities relative to the competitor",
    )

    threats: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="SWOT — threats the competitor poses to the user's business",
    )

    pricing_analysis: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="AI analysis of the competitor's pricing strategy and tiers",
    )

    feature_analysis: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Comparison of the competitor's product features vs user's",
    )

    market_position: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Assessment of the competitor's positioning in the market",
    )

    # ------------------------------------------------------------------
    # Raw AI Output — preserved for debugging, re-processing, auditing
    # ------------------------------------------------------------------
    raw_ai_response: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Full unprocessed output from the AI model for audit/debug",
    )

    # ------------------------------------------------------------------
    # Generated PDF artifact path
    # ------------------------------------------------------------------
    pdf_path: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True,
        comment="File path to generated PDF report",
    )

    # ------------------------------------------------------------------
    # Audit Timestamp
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Timestamp of report creation, set by database at INSERT",
    )

    # ------------------------------------------------------------------
    # Relationships
    # Many-to-One: Report -> Competitor (each report belongs to one competitor)
    # ------------------------------------------------------------------
    competitor: Mapped["Competitor"] = relationship(
        "Competitor",
        back_populates="reports",
        lazy="selectin",
    )

    def __repr__(self) -> str:
        return (
            f"<Report id={self.id!r} competitor_id={self.competitor_id!r}"
            f" status={self.status!r}>"
        )

