"""Add competitor_snapshots and change_events tables

Revision ID: a3f8c1e2b9d4
Revises: f81252b926ba
Create Date: 2026-07-30 22:07:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f8c1e2b9d4'
down_revision: Union[str, Sequence[str], None] = 'f81252b926ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create competitor_snapshots and change_events tables."""

    # ── competitor_snapshots ──────────────────────────────────────────────────
    op.create_table(
        'competitor_snapshots',
        sa.Column(
            'id', sa.String(length=36), nullable=False,
            comment='UUID primary key, generated by application layer',
        ),
        sa.Column(
            'competitor_id', sa.String(length=36), nullable=False,
            comment='Foreign key referencing competitors.id',
        ),
        sa.Column(
            'content_hash', sa.String(length=64), nullable=False,
            comment='SHA256 hex digest of combined crawled content for duplicate detection',
        ),
        sa.Column(
            'homepage_content', sa.Text(), nullable=True,
            comment='Raw markdown content scraped from competitor homepage',
        ),
        sa.Column(
            'pricing_content', sa.Text(), nullable=True,
            comment='Raw markdown content scraped from competitor pricing page',
        ),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            nullable=False, server_default=sa.text('now()'),
            comment='Timestamp when snapshot was taken',
        ),
        sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_competitor_snapshots_competitor_id'),
        'competitor_snapshots', ['competitor_id'], unique=False,
    )
    op.create_index(
        op.f('ix_competitor_snapshots_content_hash'),
        'competitor_snapshots', ['content_hash'], unique=False,
    )
    op.create_index(
        'ix_snapshots_competitor_created',
        'competitor_snapshots', ['competitor_id', 'created_at'], unique=False,
    )

    # ── change_events ─────────────────────────────────────────────────────────
    op.create_table(
        'change_events',
        sa.Column(
            'id', sa.String(length=36), nullable=False,
            comment='UUID primary key, generated by application layer',
        ),
        sa.Column(
            'competitor_id', sa.String(length=36), nullable=False,
            comment='Foreign key referencing competitors.id',
        ),
        sa.Column(
            'snapshot_id', sa.String(length=36), nullable=True,
            comment='Foreign key referencing competitor_snapshots.id',
        ),
        sa.Column(
            'category', sa.String(length=50), nullable=False,
            comment='Category of change: Pricing | Features | Homepage | Hiring | Marketing | Product | Documentation',
        ),
        sa.Column(
            'summary', sa.Text(), nullable=False,
            comment='AI-generated summary and business impact assessment of the change',
        ),
        sa.Column(
            'added_content', sa.Text(), nullable=True,
            comment='Highlights of added text/features',
        ),
        sa.Column(
            'removed_content', sa.Text(), nullable=True,
            comment='Highlights of removed text/features',
        ),
        sa.Column(
            'impact_score', sa.String(length=20), nullable=True,
            comment='Estimated business impact: High | Medium | Low',
        ),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            nullable=False, server_default=sa.text('now()'),
            comment='Timestamp when change event was created',
        ),
        sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(
            ['snapshot_id'], ['competitor_snapshots.id'], ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_change_events_competitor_id'),
        'change_events', ['competitor_id'], unique=False,
    )
    op.create_index(
        op.f('ix_change_events_snapshot_id'),
        'change_events', ['snapshot_id'], unique=False,
    )
    op.create_index(
        op.f('ix_change_events_category'),
        'change_events', ['category'], unique=False,
    )
    op.create_index(
        op.f('ix_change_events_created_at'),
        'change_events', ['created_at'], unique=False,
    )
    op.create_index(
        'ix_change_events_competitor_created',
        'change_events', ['competitor_id', 'created_at'], unique=False,
    )


def downgrade() -> None:
    """Drop change_events and competitor_snapshots tables."""
    # Drop in reverse order to respect foreign key constraints
    op.drop_index('ix_change_events_competitor_created', table_name='change_events')
    op.drop_index(op.f('ix_change_events_created_at'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_category'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_snapshot_id'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_competitor_id'), table_name='change_events')
    op.drop_table('change_events')

    op.drop_index('ix_snapshots_competitor_created', table_name='competitor_snapshots')
    op.drop_index(op.f('ix_competitor_snapshots_content_hash'), table_name='competitor_snapshots')
    op.drop_index(op.f('ix_competitor_snapshots_competitor_id'), table_name='competitor_snapshots')
    op.drop_table('competitor_snapshots')
