"""Initial

Revision ID: f81252b926ba
Revises: 
Create Date: 2026-07-30 11:26:24.468581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81252b926ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID primary key, generated by the application layer'),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address — unique login identifier"),
    sa.Column('hashed_password', sa.String(), nullable=False, comment='bcrypt-hashed password; plain text is never persisted'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='False disables login without deleting the account'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp, set by PostgreSQL at INSERT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('competitors',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID primary key, generated by application layer'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Foreign key referencing users.id'),
    sa.Column('company_name', sa.String(length=255), nullable=False, comment='Name of the competitor company'),
    sa.Column('website', sa.String(length=500), nullable=False, comment='Primary website or domain URL of the competitor'),
    sa.Column('industry', sa.String(length=150), nullable=True, comment='Industry category or market sector'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='Headquarters country or primary region'),
    sa.Column('description', sa.Text(), nullable=True, comment='Brief overview or additional notes about the competitor'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Active flag — setting False disables automated monitoring'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of creation, set by database server at INSERT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_user_id'), 'competitors', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID primary key, generated by application layer'),
    sa.Column('competitor_id', sa.String(length=36), nullable=False, comment='Foreign key to competitors.id — cascades on delete'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='AI pipeline status: pending | processing | completed | failed'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Executive summary of the competitive analysis'),
    sa.Column('strengths', sa.Text(), nullable=True, comment='SWOT — competitor strengths identified by the AI agent'),
    sa.Column('weaknesses', sa.Text(), nullable=True, comment='SWOT — competitor weaknesses identified by the AI agent'),
    sa.Column('opportunities', sa.Text(), nullable=True, comment='SWOT — market opportunities relative to the competitor'),
    sa.Column('threats', sa.Text(), nullable=True, comment="SWOT — threats the competitor poses to the user's business"),
    sa.Column('pricing_analysis', sa.Text(), nullable=True, comment="AI analysis of the competitor's pricing strategy and tiers"),
    sa.Column('feature_analysis', sa.Text(), nullable=True, comment="Comparison of the competitor's product features vs user's"),
    sa.Column('market_position', sa.Text(), nullable=True, comment="Assessment of the competitor's positioning in the market"),
    sa.Column('raw_ai_response', sa.Text(), nullable=True, comment='Full unprocessed output from the AI model for audit/debug'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of report creation, set by database at INSERT'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_competitor_created', 'reports', ['competitor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_competitor_id'), 'reports', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_competitor_id'), table_name='reports')
    op.drop_index('ix_reports_competitor_created', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_competitors_user_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
