"""
User domain — SQLAlchemy 2.0 declarative model.

This is the ONLY file modified in Milestone 1.
No repository, service, or API route is included here.
"""

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, String, func
from sqlalchemy.orm import Mapped, mapped_column

from src.database import Base


class User(Base):
    """
    ORM model representing the `users` table in PostgreSQL.

    Maps directly to a single database row. All authentication,
    querying, and persistence logic lives in separate layers
    (repository, service) — this model is purely structural.
    """

    __tablename__ = "users"

    # ------------------------------------------------------------------
    # Primary key — UUID string generated in Python before INSERT.
    # Using uuid4() ensures global uniqueness without a DB sequence,
    # which is safe across distributed systems and easier to expose
    # in APIs (no predictable integer IDs).
    # ------------------------------------------------------------------
    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        comment="UUID primary key, generated by the application layer",
    )

    # ------------------------------------------------------------------
    # Email — the user's unique identifier for login.
    # index=True creates a B-tree index in PostgreSQL so lookups by
    # email (e.g. during login) are O(log n) instead of full table scan.
    # ------------------------------------------------------------------
    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
        comment="User's email address — unique login identifier",
    )

    # ------------------------------------------------------------------
    # Hashed password — NEVER store plain text.
    # The service layer will use passlib/bcrypt to hash before saving.
    # Text length is unbounded (bcrypt output is ~60 chars, argon2 ~95).
    # ------------------------------------------------------------------
    hashed_password: Mapped[str] = mapped_column(
        String,
        nullable=False,
        comment="bcrypt-hashed password; plain text is never persisted",
    )

    # ------------------------------------------------------------------
    # Soft-delete / account status flag.
    # Setting is_active=False disables the account without losing data.
    # The auth layer checks this before issuing JWT tokens.
    # ------------------------------------------------------------------
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
        comment="False disables login without deleting the account",
    )

    # ------------------------------------------------------------------
    # Audit timestamp — set by PostgreSQL at INSERT time via NOW().
    # server_default means the DB writes this, so it's reliable even
    # if the application clock drifts or the column is omitted on INSERT.
    # timezone=True stores as TIMESTAMPTZ (UTC-aware) in PostgreSQL.
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Row creation timestamp, set by PostgreSQL at INSERT",
    )

    def __repr__(self) -> str:
        return f"<User id={self.id!r} email={self.email!r} active={self.is_active}>"

