"""Competitor domain — SQLAlchemy 2.0 declarative model."""

from datetime import datetime
import uuid

from sqlalchemy import Boolean, DateTime, ForeignKey, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.database import Base


class Competitor(Base):
    """ORM model representing the `competitors` table in PostgreSQL.

    Stores target competitor company profiles monitored by platform users.
    """

    __tablename__ = "competitors"

    # ------------------------------------------------------------------
    # Primary Key — UUID string generated in Python before INSERT
    # ------------------------------------------------------------------
    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        comment="UUID primary key, generated by application layer",
    )

    # ------------------------------------------------------------------
    # Foreign Key — references users.id (owner of this competitor profile)
    # ------------------------------------------------------------------
    user_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Foreign key referencing users.id",
    )

    # ------------------------------------------------------------------
    # Core Company Details
    # ------------------------------------------------------------------
    company_name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="Name of the competitor company",
    )

    website: Mapped[str] = mapped_column(
        String(500),
        nullable=False,
        comment="Primary website or domain URL of the competitor",
    )

    industry: Mapped[str | None] = mapped_column(
        String(150),
        nullable=True,
        default=None,
        comment="Industry category or market sector",
    )

    country: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        default=None,
        comment="Headquarters country or primary region",
    )

    description: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        default=None,
        comment="Brief overview or additional notes about the competitor",
    )

    # ------------------------------------------------------------------
    # Active Monitoring Status Flag
    # ------------------------------------------------------------------
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
        comment="Active flag — setting False disables automated monitoring",
    )

    # ------------------------------------------------------------------
    # Audit Timestamp
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Timestamp of creation, set by database server at INSERT",
    )

    # ------------------------------------------------------------------
    # Relationships
    # Many-to-One:  Competitor -> User
    # One-to-Many:  Competitor -> Reports (one competitor has many reports)
    # ------------------------------------------------------------------
    user: Mapped["User"] = relationship("User", lazy="selectin")

    reports: Mapped[list["Report"]] = relationship(
        "Report",
        back_populates="competitor",
        lazy="select",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<Competitor id={self.id!r} company={self.company_name!r} user_id={self.user_id!r}>"

